import type { BrowseItem, Category, Certificate } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "helmet",
    name: "Helmet",
    nameZh: "头盔",
    slug: "helmet",
    count: 207,
    children: [
      {
        id: "equestrian",
        name: "Equestrian Helmet",
        nameZh: "马术头盔",
        slug: "equestrian",
        count: 150,
      },
      {
        id: "sports",
        name: "Sports Helmet",
        nameZh: "运动头盔",
        slug: "sports",
        count: 57,
      },
    ],
  },
  {
    id: "protective-gear",
    name: "Protective Gear",
    nameZh: "防护装备",
    slug: "protective-gear",
    count: 42,
  },
];

const companies = {
  rif: {
    id: "0200020",
    name: "Shaoxing RIF Sports Goods Co., Ltd",
    nameZh: "绍兴锐孚运动用品有限公司",
    country: "China",
  },
  cavalli: {
    id: "0201038",
    name: "Cavalli Group B.V.",
    nameZh: "卡瓦利集团",
    country: "Netherlands",
  },
  qilin: {
    id: "0201028",
    name: "Qilin Sports",
    nameZh: "麒麟运动",
    country: "China",
  },
  kylin: {
    id: "0201036",
    name: "Kylin Sports",
    nameZh: "凯麟运动",
    country: "China",
  },
  brothers: {
    id: "0201037",
    name: "Brothers Sports",
    nameZh: "兄弟运动",
    country: "China",
  },
};

export const mockCertificates: Certificate[] = [
  {
    id: "6161",
    name: "F20-201AL Series Certificate",
    nameZh: "F20-201AL 系列证书",
    productName: "Equestrian Helmet",
    productNameZh: "马术头盔",
    certifiedType: "CE",
    description: "CE certified equestrian protective headgear for horse riding activities.",
    descriptionZh: "适用于马术骑乘活动的 CE 认证防护头盔。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.rif.id,
    company: companies.rif,
    model: "F20-201AL / F20-201AE / F20-202AL",
    certificateNumber: "CE-2024-00128",
    issueDate: "2024-01-12",
    expiryDate: "2026-12-31",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Verified against submitted PDF copy",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6161_1.png",
    previewImages: [
      "/certs/images/20_100_52_6161_1.png",
      "/certs/images/20_100_52_6160_1.png",
    ],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 1250,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "6160",
    name: "F11 Plus Series Certificate",
    nameZh: "F11 Plus 系列证书",
    productName: "Riding Helmet",
    productNameZh: "骑乘头盔",
    certifiedType: "CE",
    description: "Advanced riding helmet for professional riders and training use.",
    descriptionZh: "适用于专业骑手和训练场景的高级骑乘头盔。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.rif.id,
    company: companies.rif,
    model: "F11 Plus-112A / F11 Plus-118A",
    certificateNumber: "CE-2024-00114",
    issueDate: "2024-02-05",
    expiryDate: "2026-08-10",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Approved after manual review",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6160_1.png",
    previewImages: ["/certs/images/20_100_52_6160_1.png"],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 890,
    createdAt: "2024-02-20",
    updatedAt: "2024-02-20",
  },
  {
    id: "6159",
    name: "F35 Plus Certificate",
    nameZh: "F35 Plus 证书",
    productName: "Premium Riding Helmet",
    productNameZh: "高阶骑乘头盔",
    certifiedType: "CE",
    description: "Premium riding helmet with extended ventilation structure.",
    descriptionZh: "带增强通风结构的高阶骑乘头盔。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.rif.id,
    company: companies.rif,
    model: "F35 Plus-357A",
    certificateNumber: "CE-2023-00977",
    issueDate: "2023-03-01",
    expiryDate: "2025-03-01",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Archived certificate, pending renewal",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6159_1.png",
    previewImages: ["/certs/images/20_100_52_6159_1.png"],
    languages: ["EN"],
    status: "EXPIRED",
    viewCount: 670,
    createdAt: "2024-03-10",
    updatedAt: "2024-03-10",
  },
  {
    id: "6158",
    name: "F60-608A Certificate",
    nameZh: "F60-608A 证书",
    productName: "Competition Helmet",
    productNameZh: "比赛头盔",
    certifiedType: "CE",
    description: "Lightweight competition helmet for equestrian events.",
    descriptionZh: "适用于马术赛事的轻量比赛头盔。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.rif.id,
    company: companies.rif,
    model: "F60-608A",
    certificateNumber: "CE-2024-00103",
    issueDate: "2024-04-05",
    expiryDate: "2026-10-01",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Approved after file comparison",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6158_1.png",
    previewImages: ["/certs/images/20_100_52_6158_1.png"],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 540,
    createdAt: "2024-04-05",
    updatedAt: "2024-04-05",
  },
  {
    id: "6156",
    name: "F70-709A Certificate",
    nameZh: "F70-709A 证书",
    productName: "Professional Safety Helmet",
    productNameZh: "专业安全头盔",
    certifiedType: "CE",
    description: "Professional grade safety helmet for regular riding use.",
    descriptionZh: "适用于日常骑乘的专业级安全头盔。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.rif.id,
    company: companies.rif,
    model: "F70-709A",
    certificateNumber: "CE-2024-00101",
    issueDate: "2024-05-12",
    expiryDate: "2026-11-20",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Primary active model",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6156_1.png",
    previewImages: ["/certs/images/20_100_52_6156_1.png"],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 430,
    createdAt: "2024-05-12",
    updatedAt: "2024-05-12",
  },
  {
    id: "71",
    name: "F70-709 Multi-language Certificate",
    nameZh: "F70-709 多语言证书",
    productName: "Multi-language Equestrian Helmet",
    productNameZh: "多语言马术头盔",
    certifiedType: "CE",
    description: "A multi-language version of the equestrian helmet certificate for EU distribution.",
    descriptionZh: "面向欧盟分销的多语言版本马术头盔证书。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.rif.id,
    company: companies.rif,
    model: "F70-709 Multi",
    certificateNumber: "CE-2024-00132",
    issueDate: "2024-06-01",
    expiryDate: "2026-12-31",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Language pack updated",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_71_1.jpeg",
    previewImages: ["/certs/images/20_100_52_71_1.jpeg"],
    languages: ["EN", "NL", "PT", "ES", "SE", "IT"],
    status: "ACTIVE",
    viewCount: 380,
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01",
  },
  {
    id: "608",
    name: "F60-608 Certificate",
    nameZh: "F60-608 证书",
    productName: "Premium Equestrian Helmet",
    productNameZh: "高端马术头盔",
    certifiedType: "CE",
    description: "Cavalli Group premium helmet certificate for EU market entry.",
    descriptionZh: "卡瓦利集团面向欧盟市场的高端头盔证书。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.cavalli.id,
    company: companies.cavalli,
    model: "F60-608",
    certificateNumber: "CE-2024-00157",
    issueDate: "2024-07-01",
    expiryDate: "2026-09-18",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Imported document approved",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6158_1.png",
    previewImages: ["/certs/images/20_100_52_6158_1.png"],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 320,
    createdAt: "2024-07-01",
    updatedAt: "2024-07-01",
  },
  {
    id: "709",
    name: "F70-709 Certificate",
    nameZh: "F70-709 证书",
    productName: "Competition Series Helmet",
    productNameZh: "竞技系列头盔",
    certifiedType: "CE",
    description: "Competition series certificate maintained by Cavalli Group.",
    descriptionZh: "由卡瓦利集团维护的竞技系列证书。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.cavalli.id,
    company: companies.cavalli,
    model: "F70-709",
    certificateNumber: "CE-2024-00161",
    issueDate: "2024-08-01",
    expiryDate: "2026-10-20",
    reviewStatus: "PENDING",
    uploadedBy: "Compliance Admin",
    auditStatusNote: "Pending supporting annex upload",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6156_1.png",
    previewImages: ["/certs/images/20_100_52_6156_1.png"],
    languages: ["EN"],
    status: "PENDING",
    viewCount: 280,
    createdAt: "2024-08-01",
    updatedAt: "2024-08-01",
  },
  {
    id: "qilin-001",
    name: "Qilin Helmet Series Certificate",
    nameZh: "麒麟头盔系列证书",
    productName: "Equestrian Helmet",
    productNameZh: "马术头盔",
    certifiedType: "CE",
    description: "Qilin Sports certificate covering standard equestrian helmet models.",
    descriptionZh: "覆盖标准马术头盔型号的麒麟运动证书。",
    categoryId: "helmet",
    category: { id: "helmet", name: "Helmet", nameZh: "头盔", slug: "helmet" },
    companyId: companies.qilin.id,
    company: companies.qilin,
    model: "QH-220",
    certificateNumber: "CE-2024-00170",
    issueDate: "2024-10-01",
    expiryDate: "2026-10-01",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Approved with attachment set A",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6161_1.png",
    previewImages: ["/certs/images/20_100_52_6161_1.png"],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 220,
    createdAt: "2024-10-01",
    updatedAt: "2024-10-01",
  },
  {
    id: "kylin-001",
    name: "Kylin Helmet Certificate",
    nameZh: "凯麟头盔证书",
    productName: "Protective Riding Helmet",
    productNameZh: "防护骑乘头盔",
    certifiedType: "CE",
    description: "Protective riding helmet certificate for export batch K-11.",
    descriptionZh: "用于出口批次 K-11 的防护骑乘头盔证书。",
    categoryId: "protective-gear",
    category: { id: "protective-gear", name: "Protective Gear", nameZh: "防护装备", slug: "protective-gear" },
    companyId: companies.kylin.id,
    company: companies.kylin,
    model: "KY-118",
    certificateNumber: "CE-2024-00178",
    issueDate: "2024-11-01",
    expiryDate: "2027-01-15",
    reviewStatus: "APPROVED",
    uploadedBy: "Admin",
    auditStatusNote: "Batch export documentation complete",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6159_1.png",
    previewImages: ["/certs/images/20_100_52_6159_1.png"],
    languages: ["EN"],
    status: "ACTIVE",
    viewCount: 200,
    createdAt: "2024-11-01",
    updatedAt: "2024-11-01",
  },
  {
    id: "brothers-001",
    name: "Brothers Helmet Certificate",
    nameZh: "兄弟头盔证书",
    productName: "Riding Helmet",
    productNameZh: "骑乘头盔",
    certifiedType: "CE",
    description: "Initial compliance filing for Brothers Sports helmet export program.",
    descriptionZh: "兄弟运动头盔出口项目的初始合规备案。",
    categoryId: "protective-gear",
    category: { id: "protective-gear", name: "Protective Gear", nameZh: "防护装备", slug: "protective-gear" },
    companyId: companies.brothers.id,
    company: companies.brothers,
    model: "BH-01",
    certificateNumber: "CE-2024-00184",
    issueDate: "2024-12-01",
    expiryDate: "2026-12-01",
    reviewStatus: "PENDING",
    uploadedBy: "Compliance Admin",
    auditStatusNote: "Awaiting final reviewer signature",
    pdfUrl: "/certs/pdfs/20260505090148_7349.pdf",
    imageUrl: "/certs/images/20_100_52_6160_1.png",
    previewImages: ["/certs/images/20_100_52_6160_1.png"],
    languages: ["EN"],
    status: "PENDING",
    viewCount: 180,
    createdAt: "2024-12-01",
    updatedAt: "2024-12-01",
  },
];

export const browseCompanies: BrowseItem[] = [
  { id: "rif", label: companies.rif.name, labelZh: companies.rif.nameZh, count: 141, meta: "China" },
  { id: "qilin", label: companies.qilin.name, labelZh: companies.qilin.nameZh, count: 42, meta: "China" },
  { id: "cavalli", label: companies.cavalli.name, labelZh: companies.cavalli.nameZh, count: 15, meta: "Netherlands" },
  { id: "kylin", label: companies.kylin.name, labelZh: companies.kylin.nameZh, count: 3, meta: "China" },
];

export const browseCategories: BrowseItem[] = [
  { id: "helmet", label: "Helmet", labelZh: "头盔", count: 207, meta: "Riding / CE" },
  { id: "equestrian", label: "Equestrian Helmet", labelZh: "马术头盔", count: 150, meta: "Core category" },
  { id: "protective-gear", label: "Protective Gear", labelZh: "防护装备", count: 42, meta: "Related products" },
];

export const browseCountries: BrowseItem[] = [
  { id: "china", label: "China", labelZh: "中国", count: 189, meta: "Manufacturing origin" },
  { id: "netherlands", label: "Netherlands", labelZh: "荷兰", count: 18, meta: "Importer / filing base" },
];

export const libraryStats = [
  { id: "certificates", value: "200+" },
  { id: "companies", value: "40+" },
  { id: "countries", value: "12" },
];

export const recentCertificates = mockCertificates.slice(0, 6);
export const featuredCertificates = mockCertificates.slice(0, 4);
export const verifiedCertificates = mockCertificates.filter((cert) => cert.reviewStatus === "APPROVED").slice(0, 5);
